In [1]:
#%%capture

# Comment this out if you don't want to install pennylane from this notebook
!pip install pennylane

# Comment this out if you don't want to install matplotlib from this notebook
!pip install matplotlib

     |████████████████████████████████| 409kB 5.7MB/s 
  Created wheel for pennylane: filename=PennyLane-0.14.1-cp36-none-any.whl size=481981 sha256=056b07ff3de324d5a34a8b8f2f8a47a23673ded87a5b62e42c9090dcebfc6172
  Stored in directory: /root/.cache/pip/wheels/6e/a9/c9/04941d6dd58b3c111cbd1389bf63ba1b23362c137359af4626
Successfully built pennylane


# Differentiable quantum computing with PennyLane

In this tutorial we will:

* learn step-by-step how quantum computations are implemented in PennyLane,
* understand parameter-dependent quantum computations ("variational circuits"), 
* build our first quantum machine learning model, and
* compute its gradient.

We need the following imports:

In [2]:
import pennylane as qml
from pennylane import numpy as np

## 1. Quantum nodes

In PennyLane, a *quantum node* is a computational unit that involves the construction, evaluation, pre- and postprocessing of quantum computations.

A quantum node consists of a *quantum function* that defines a circuit, as well as a *device* on which it is run. 

There is a growing [device ecosystem](https://pennylane.ai/plugins.html) which allows you to change only one line of code to dispatch your quantum computation to local simulators, remote simulators and remote hardware from different vendors.

Here we will use the built-in `default.qubit` device.

In [3]:
dev = qml.device('default.qubit', wires=2)

To combine the device with a quantum function to a quantum node we can use the `qml.qnode` decorator. The function can then be evaluated as if it was any other python function. Internally, it will construct a circuit and run it on the device.

In [4]:
@qml.qnode(dev)
def circuit():
    qml.Hadamard(wires=0)
    return qml.probs(wires=[0, 1])

circuit()

tensor([0.5, 0. , 0.5, 0. ], requires_grad=True)

## 2. Building quantum circuits

### The initial state

<br />
<img src="figures/1.png" width="500" height="100">
<br />

The initial state has 100% probability to be measured in the "0..0" configuration. Let's see how we can verify this with PennyLane.

In [5]:
@qml.qnode(dev)
def circuit():
    return qml.probs(wires=[0, 1])

circuit()

tensor([1., 0., 0., 0.], requires_grad=True)

The internal state vector that we use to mathematically keep track of probabilities is complex-valued. Since `default.qubit` is a simulator we can have a look at the state, for example by checking the device's `state` attribute.

In [6]:
dev.state

tensor([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], requires_grad=True)

### Unitary evolutions

<br />
<img src="figures/2.png" width="500">
<br />

Quantum circuits are represented by unitary matrices. We can evolve the initial state by an arbitrary unitrary matrix as follows:

In [7]:
s = 1/np.sqrt(2)
U = np.array([[0., -s, 0.,  s],
              [ s, 0., -s, 0.],
              [ s, 0.,  s, 0.],
              [0., -s, 0., -s]])

@qml.qnode(dev)
def circuit():
    qml.QubitUnitary(U, wires=[0, 1])
    return qml.probs(wires=[0, 1])

circuit()

tensor([0. , 0.5, 0.5, 0. ], requires_grad=True)

The internal quantum state changed.

In [8]:
dev.state

tensor([0.        +0.j, 0.70710678+0.j, 0.70710678+0.j, 0.        +0.j], requires_grad=True)

### Measurements sample outcomes from the distribution

<br />
<img src="figures/3.png" width="500">
<br />

The most common measurement takes samples $-1, 1$ from the "Pauli-Z" observable. The samples indicate if the qubit was measured in state $| 0 \rangle$ or $| 1 \rangle$.

In [9]:
@qml.qnode(dev)
def circuit():
    qml.QubitUnitary(U, wires=[0, 1])
    return qml.sample(qml.PauliZ(wires=0)), qml.sample(qml.PauliZ(wires=1))

circuit()

tensor([[-1,  1,  1, ...,  1, -1,  1],
        [ 1, -1, -1, ..., -1,  1, -1]], requires_grad=True)

The quantum state should be still the same as above.

In [10]:
dev.state

tensor([0.        +0.j, 0.70710678+0.j, 0.70710678+0.j, 0.        +0.j], requires_grad=True)

### Computing expectation values 

<br />
<img src="figures/4.png" width="500">
<br />

When we want outputs of computations to be deterministic, we often interpret the expected measurement outcome as the result. This value is estimated by taking lots of samples and averaging over them.

In [11]:
@qml.qnode(dev)
def circuit():
    qml.QubitUnitary(U, wires=[0, 1])
    return qml.expval(qml.PauliZ(wires=0)), qml.expval(qml.PauliZ(wires=1))

circuit()

tensor([0., 0.], requires_grad=True)

Again, the quantum state should be the same as above.

In [12]:
dev.state

tensor([0.        +0.j, 0.70710678+0.j, 0.70710678+0.j, 0.        +0.j], requires_grad=True)

### Quantum circuits are decomposed into gates

<br />
<img src="figures/5.png" width="500">
<br />

Quantum circuits rarely consist of one large unitary (which quickly becomes intractably large as the number of qubits grow). Instead, they are composed of *quantum gates*.

In [13]:
@qml.qnode(dev)
def circuit():
    qml.PauliX(wires=0)
    qml.CNOT(wires=[0,1])
    qml.Hadamard(wires=0)
    qml.PauliZ(wires=1)
    return qml.expval(qml.PauliZ(wires=0)), qml.expval(qml.PauliZ(wires=1))

circuit()

tensor([ 0., -1.], requires_grad=True)

### Some gates depend on "control" parameters

<br />
<img src="figures/6.png" width="500">
<br />

To train circuits, there is a special subset of gates which is of particular interest: the Pauli rotation gates. These "rotate" a special representation of the quantum state around a specific axis. The gates depend on a scalar parameter which is the angle of the rotation. 

In [14]:
@qml.qnode(dev)
def circuit(w1, w2):
    qml.RX(w1, wires=0)
    qml.CNOT(wires=[0,1])
    qml.RY(w2, wires=1)
    return qml.expval(qml.PauliZ(wires=0)), qml.expval(qml.PauliZ(wires=1))

circuit(1.2, 1.3)

tensor([0.36235775, 0.09693027], requires_grad=True)

The names `w1`, `w2` are already suggestive that these can be used like the trainable parameters of a classical machine learning model. But we could also call the control parameters `x1`, `x2` and encode data features into quantum states. 

## 3. A full quantum machine learning model and its gradient

Finally, we can use pre-coded routines or [templates](https://pennylane.readthedocs.io/en/stable/introduction/templates.html) to conveniently build full quantum machine learning model that include a data encoding part, and a trainable part.

<br />
<img src="figures/7.png" width="500">
<br />

Here, we will use the `AngleEmbedding` template to load the data, and the `BasicEntanglingLayers` as the trainable part of the circuit.

In [15]:
@qml.qnode(dev)
def quantum_model(x, w):
    qml.templates.AngleEmbedding(x, wires=[0, 1])
    qml.templates.BasicEntanglerLayers(w, wires=[0, 1])
    return qml.expval(qml.PauliZ(wires=0))


x = np.array([0.1, 0.2], requires_grad=False)
w = np.array([[-2.1, 1.2], [-1.4, -3.9], [0.5, 0.2]])

quantum_model(x, w)

tensor(0.012023, requires_grad=True)

We can draw the circuit.

In [16]:
print(quantum_model.draw())

 0: ──RX(0.1)──RX(-2.1)──╭C──RX(-1.4)──╭C──RX(0.5)──╭C──┤ ⟨Z⟩ 
 1: ──RX(0.2)──RX(1.2)───╰X──RX(-3.9)──╰X──RX(0.2)──╰X──┤     



The best thing is that by using PennyLane, we can easily compute its gradient!

In [17]:
gradient_fn = qml.grad(quantum_model)

gradient_fn(x, w)

(array([[ 1.69541373e-01, -2.77555756e-17],
        [ 6.97079563e-02,  2.94902991e-17],
        [ 1.69541373e-01,  1.90819582e-17]]),)

This allows us to slot the quantum circuit into the machine learning example from the previous notebook.

#  TASKS 

1. Copy and paste the code from the previous notebook to here and replace the classical model by 
   the `quantum_model` function. This will allow you to train the model!

2. Add a bias term to the quantum model.

A potential solution of 1 & 2 together:

In [18]:
n_samples = 100
X0 = np.array([[np.random.normal(loc=-1, scale=1), 
                np.random.normal(loc=1, scale=1)] for i in range(n_samples//2)]) 
X1 = np.array([[np.random.normal(loc=1, scale=1), 
                np.random.normal(loc=-1, scale=1)] for i in range(n_samples//2)]) 

X = np.concatenate([X0, X1], axis=0)
Y = np.concatenate([-np.ones(50), np.ones(50)], axis=0)
data = list(zip(X, Y))

def model_with_bias(x, w, b):
    return quantum_model(x, w) + b

def loss(a, b):
    return (a - b)**2

def average_loss(w, b, data):
    c = 0
    for x, y in data:
        prediction = model_with_bias(x, w, b)
        c += loss(prediction, y)
    return c/len(data)

gradient_fn_w = qml.grad(average_loss, argnum=0)
gradient_fn_b = qml.grad(average_loss, argnum=1)

w_init = np.random.random(size=(3, 2))
w = np.array(w_init)
b = np.array(0.0) # start with zero bias

for i in range(15):
    w_new = w - 0.05*gradient_fn_w(w, b, data)
    b_new = b - 0.05*gradient_fn_b(w, b, data)
    print(average_loss(w_new, b_new, data))
    w = w_new
    b = b_new

2.1950046098627416
2.1487563225102497
2.097419031792551
2.0410097679675143
1.9797841866965666
1.9142635093055458
1.8452402100888687
1.7737548977758981
1.7010409708940477
1.628440018808254
1.5572980635173963
1.4888582614495711
1.4241674230815307
1.3640107426141581
1.3088824011456581


3. Replace the hand-coded optimisation step by a native [PennyLane optimiser](https://pennylane.readthedocs.io/en/stable/introduction/optimizers.html).

In [19]:
opt = qml.GradientDescentOptimizer(0.05)
for i in range(15):
    
    ([w, b], cst) = opt.step_and_cost(lambda w_, b_: average_loss(w_, b_, data), w, b)
    print(cst)

1.3088824011456581
1.2589916167738568
1.214296949669864
1.174557992058918
1.1393932787933791
1.108335446179102
1.0808779682677996
1.0565110144694834
1.0347464075777997
1.0151331243799258
0.997265403564296
0.98078556984829
0.9653834084721672
0.9507935255068983
0.9367917270007219


4. Rewrite the entire example in PyTorch. 

   Tipp: You must set the qnode to the correct interface via `@qml.qnode(dev, interface='tf')`.

In [20]:
import torch

data = [[torch.tensor(x), torch.tensor(y)] for x, y in data]


@qml.qnode(dev, interface='torch')
def quantum_model(x, w):
    qml.templates.AngleEmbedding(x, wires=[0, 1])
    qml.templates.BasicEntanglerLayers(w, wires=[0, 1])
    return qml.expval(qml.PauliZ(wires=0))

def average_loss(w, data):
    c = 0
    for x, y in data:
        prediction = quantum_model(x, w)
        c += loss(prediction, y)
    return c/len(data)

w_init = np.random.random(size=(3, 2))

w = torch.tensor(w_init, requires_grad=True)

opt = torch.optim.Adam([w], lr = 0.1)

# One way of optimising is to use closures
def closure():
    opt.zero_grad()
    loss = average_loss(w, data)
    loss.backward()
    return loss

for i in range(15):
    opt.step(closure)
    
    print(average_loss(w, data))
    

tensor(1.8534, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.6430, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.4323, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.2368, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(1.0707, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.9447, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.8627, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.8192, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.8009, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7926, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7835, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7692, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7499, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7283, dtype=torch.float64, grad_fn=<DivBackward0>)
tensor(0.7075, dtype=torch.float64, grad_fn=<DivBackward0>)
